scoreboard-title: '&c&lSquads'
map: 1

#Timer duration is measured in seconds.
timers:
 pvp-timer: 1800
 pearl: 16

#The spawn location; x and z are the coordinates of the corners.
spawn:
 corner-1:
  x: 75
  z: 75
 corner-2:
  x: -74
  z: -74