scoreboard-title: '&c&lSquads'
map: 1

#The map kit
map-kit:
 protection: 1
 sharpness: 2

#Timer duration is measured in seconds.
timers:
 pvp-timer: 1800
 combat-tag: 30
 pearl: 16

#The spawn location is the coordinates for where the player spawns in; the corners are the dimensions of the spawn around 0, 0
spawn:
 corner-1:
  x: 75
  z: 75
 corner-2:
  x: -75
  z: -75
 spawn-location:
  x: 0
  y: 76
  z: 0